###########################################
# date:2025_11_10
# 用于bi_lstm的config参数配置文件
############################################

# 模型名称
model_name: "bi_lstm"
device: "cuda"

# 模型结构
model:
  embed_dims: 64
  hidden_dims: 128
  n_layers: 2
  dropout: 0.2
  max_len: 80

# 训练参数
train:
  batch_size: 32
  epochs: 100
  lr: 1e-3
  k_folds: 3
  clip_grad: 1.0
  random_state : 2025

# 微调参数
fine_tune:
  batch_size: 16
  epochs: 100
  lr: 1e-4
  clip_grad: 0.5      # 可微调梯度裁剪
  save_name: "{model_name}_finetuned.pt"

# 生成参数
generate:
  num_samples: 1000
  temperature: 1.0
  top_k: 10
  max_len: 80

# 路径配置
paths:
  data_file: "./data/htvs_molecules_with_selfies.csv"
  fine_data_file : "./data/sp_molecules_with_selfies.csv"
  save_dir: "./model/{model_name}"
  log_dir: "./logs/{model_name}"
